"""initial schema

Revision ID: cb2347fb7871
Revises: 
Create Date: 2026-08-25 14:26:25.029929
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'cb2347fb7871'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('exchange_credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('api_key_masked', sa.String(length=64), nullable=False),
    sa.Column('is_read_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exchange_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_credentials')),
    sa.UniqueConstraint('user_id', 'exchange', name='uq_user_exchange')
    )
    op.create_index(op.f('ix_exchange_credentials_user_id'), 'exchange_credentials', ['user_id'], unique=False)
    op.create_table('mistake_types',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mistake_types_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mistake_types')),
    sa.UniqueConstraint('user_id', 'code', name='uq_user_mistake_code')
    )
    op.create_index(op.f('ix_mistake_types_user_id'), 'mistake_types', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strategies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_strategy_name')
    )
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('trading_plans',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_per_trade_percent', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('max_daily_loss_percent', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('max_weekly_loss_percent', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=False),
    sa.Column('min_risk_reward', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('max_leverage', sa.Integer(), nullable=False),
    sa.Column('allowed_symbols', postgresql.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('allowed_timeframes', postgresql.ARRAY(sa.String(length=8)), server_default='{}', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_daily_loss_percent > 0', name=op.f('ck_trading_plans_max_daily_loss_positive')),
    sa.CheckConstraint('min_risk_reward > 0', name=op.f('ck_trading_plans_min_rr_positive')),
    sa.CheckConstraint('risk_per_trade_percent > 0 AND risk_per_trade_percent <= 100', name=op.f('ck_trading_plans_risk_per_trade_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trading_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trading_plans')),
    sa.UniqueConstraint('user_id', name=op.f('uq_trading_plans_user_id'))
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('quote_currency', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('notifications', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    op.create_table('trades',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='tradeside', native_enum=False, length=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('fees', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('pnl_percent', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('risk_percent', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('risk_reward', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('account_balance_at_entry', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('timeframe', sa.String(length=8), nullable=True),
    sa.Column('entry_reason', sa.Text(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='tradestatus', native_enum=False, length=16), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'IMPORTED', name='tradesource', native_enum=False, length=16), nullable=False),
    sa.Column('is_annotated', sa.Boolean(), nullable=False),
    sa.Column('external_position_id', sa.String(length=64), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status != 'CLOSED') OR (closed_at IS NOT NULL)", name=op.f('ck_trades_closed_trade_has_closed_at')),
    sa.CheckConstraint('leverage >= 1', name=op.f('ck_trades_leverage_at_least_one')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_trades_quantity_non_negative')),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_trades_strategy_id_strategies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trades_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades')),
    sa.UniqueConstraint('user_id', 'exchange', 'external_position_id', name='uq_trade_external_position')
    )
    op.create_index(op.f('ix_trades_opened_at'), 'trades', ['opened_at'], unique=False)
    op.create_index('ix_trades_user_closed', 'trades', ['user_id', 'closed_at'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_index('ix_trades_user_status', 'trades', ['user_id', 'status'], unique=False)
    op.create_index('ix_trades_user_strategy', 'trades', ['user_id', 'strategy_id'], unique=False)
    op.create_index('ix_trades_user_symbol', 'trades', ['user_id', 'symbol'], unique=False)
    op.create_table('trade_fills',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('fill_side', sa.Enum('ENTRY', 'EXIT', name='fillside', native_enum=False, length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_fill_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_trade_fills_fill_price_positive')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_trade_fills_fill_quantity_positive')),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_trade_fills_trade_id_trades'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trade_fills_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_fills')),
    sa.UniqueConstraint('user_id', 'exchange', 'external_fill_id', name='uq_fill_external_id')
    )
    op.create_index('ix_fills_trade', 'trade_fills', ['trade_id', 'executed_at'], unique=False)
    op.create_table('trade_mistakes',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('mistake_type_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mistake_type_id'], ['mistake_types.id'], name=op.f('fk_trade_mistakes_mistake_type_id_mistake_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_trade_mistakes_trade_id_trades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_mistakes')),
    sa.UniqueConstraint('trade_id', 'mistake_type_id', name='uq_trade_mistake')
    )
    op.create_index(op.f('ix_trade_mistakes_mistake_type_id'), 'trade_mistakes', ['mistake_type_id'], unique=False)
    op.create_index(op.f('ix_trade_mistakes_trade_id'), 'trade_mistakes', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_mistakes_trade_id'), table_name='trade_mistakes')
    op.drop_index(op.f('ix_trade_mistakes_mistake_type_id'), table_name='trade_mistakes')
    op.drop_table('trade_mistakes')
    op.drop_index('ix_fills_trade', table_name='trade_fills')
    op.drop_table('trade_fills')
    op.drop_index('ix_trades_user_symbol', table_name='trades')
    op.drop_index('ix_trades_user_strategy', table_name='trades')
    op.drop_index('ix_trades_user_status', table_name='trades')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index('ix_trades_user_closed', table_name='trades')
    op.drop_index(op.f('ix_trades_opened_at'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('user_settings')
    op.drop_table('trading_plans')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_mistake_types_user_id'), table_name='mistake_types')
    op.drop_table('mistake_types')
    op.drop_index(op.f('ix_exchange_credentials_user_id'), table_name='exchange_credentials')
    op.drop_table('exchange_credentials')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
